### ISSUE TITLE
circular dependency in SuperClimateDataset

### ISSUE THREAD

**Issue by FelixNahrstedt** [RolnickLab/ClimateSet#10]
The class SuperClimateDataset uses both class Input4MipsDataset(SuperClimateDataset) as well as class CMIP6Dataset(SuperClimateDataset) during construction even though they itself inherit from SuperClimateDataset, leading to unexpected behaviour (especially when using multiple workers or parallized training I believe).

 `
    class SuperClimateDataset(torch.utils.data.Dataset):

    def __init__(
        [...]
    ):
        [...]
        # creates list of input4mips (one per unique openburning spec)
        self.input4mips_ds = dict()
        for spec in set(self.openburning_specs):
            self.input4mips_ds[spec] = Input4MipsDataset(
                variables=in_variables, openburning_specs=spec, **ds_kwargs
            )
        [...]
  `

`class CMIP6Dataset(SuperClimateDataset):
`

`class Input4MipsDataset(SuperClimateDataset):
`

For further details see: [https://github.com/RolnickLab/ClimateSet/blame/main/emulator/src/data/super_climate_dataset.py](url)

**Comment by f-PLT** [comment]
Ok, this is very early and a preliminary statement, as there are probably a lot of nuances I don't know about, but:

I'm not sure `Input4MipsDataset` and `CMIP6Dataset`  really need to inherit from `SuperClimateDataset`, conceptually speaking, especially as `SuperClimateDataset` is composed of them.

`Input4MipsDataset` and `CMIP6Dataset` also have their own `__init__()` function, so it overrides `SuperClimateDataset`'s own, and the functions they use/inherit from it could probably be generalized or taken out of the class (as pure functions)

The other way about it could be to have a "BaseSuperDataset" class, which all three would inherit from, that would be strictly for data structure and utility functions, and keep the composition approach of `SuperClimateDataset`

Ideally, however, there should be no inheritance shared between a class and it's components (only composition), and inheritance should be avoided whenever possible, as it makes it difficult to maintain in the long run.

Side note : There are 2 of each classes `Input4MipsDataset` and `CMIP6Dataset`, one set in `src/data/climate_dataset.py` and the other in `src/data/super_climate_dataset.py`. I would strongly recommend there be a change of names for one of the sets, as it can cause both confusion and namespace collisions. The class pair in `src/data/climate_dataset.py` also appear to have the same inheritance dynamic explained in this issue, and could probably cause the same problems.

That's all for now!

**Comment by FelixNahrstedt** [comment]
As discussed last week on the meeting: Relevant files from Merge #11 are emulator/src/datamodules/super_climate_datamodule.py as well as emulator/src/data/super_climate_dataset.py - I opened a conversation [here](https://github.com/RolnickLab/ClimateSet/pull/11) ...Wasnt sure how I put you for review on individual commits when I merge multiple commits at once...hope you can have a look anyways. The overall code for the datamodule is still not perfect and a bit too long but I tried to at least keep the changes I made more or less well documented. 

Changes: 
**super_climate_datamodule**: ABC_Climate_Dataset that all datasets (as well as the combined dataset) inherit from, index_manager is now used for indexing and dataset manipulation tasks

**super_climate_dataset**: StateManager class is defined that organises states and indices of dataset classes, data is automatically in mode train now but can be switched to Validation any time (similar to before)
