### ISSUE TITLE
Which LICENSE is associated with this codebase?

### ISSUE THREAD

**Issue by blutjens** [RolnickLab/ClimateSet#14]
I could not find a LICENSE file in this codebase and wondered under which license the code is published? Technically, if this codebase doesn't have a license file it would fall under an 'all rights reserved' status, as far as I know . Thank you!

**Comment by liellnima** [comment]
Thank you for pointing this out! I will add a license tomorrow, after having discussed this with the team. I expect it will be a [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) or [MIT](https://choosealicense.com/licenses/mit/), but I will let you know asap and upload a LICENSE file.

**Comment by liellnima** [comment]
Update: I am waiting for the okay of one person (by the end of this week), and will upload the license once I got that!

**Comment by liellnima** [comment]
See #19
