### ISSUE TITLE
Questions regarding evaluation metrics.

### ISSUE THREAD

**Issue by hassony2** [RolnickLab/ClimateSet#18]
Hi !

Thank you for the great work and the exciting benchmark :)

I have a couple of questions regarding the RMSE reported in the paper:
1. Could you confirm that the weighted RMSE you are reporting in the tables and figures the one computed by [LLweighted_RMSE_Climax](https://github.com/RolnickLab/ClimateSet/blob/66d724026012d5671817eaf0460ea720b95d8f9f/emulator/src/core/metrics.py#L146)  ? This is what I understand from reading the paper :)
 
2. Are the numbers in [internal/scores](https://github.com/RolnickLab/ClimateSet/tree/66d724026012d5671817eaf0460ea720b95d8f9f/internal/scores) the ones reported in the paper ? I tried matching the exact values to the tables, and did not succeed, but maybe I am misunderstanding something !

Also, I suspect there might be an error in the implementation of metric [LLWeighted_RMSE_WheatherBench](https://github.com/RolnickLab/ClimateSet/blob/66d724026012d5671817eaf0460ea720b95d8f9f/emulator/src/core/metrics.py#L109) as 
 in   `weights = (np.cos(lats) / np.cos(lats)).mean()` np.cos(lats) / np.cos(lats) would always evaluate to an array of 1 ?

**Comment by blutjens** [comment]
For what it's worth, I tested the UNet implementation and got similar scores for the NorESM2-LM in Figure 6 which matches scores in Table 5. And, that is with the LLweighted_RMSE_Climax. I believe that a colleague has been able to reproduce the results of the ClimaX column with the LLweighted_RMSE_Climax. However, there is the remaining issue of the missing longitude dimension that we both have been facing (see [issue 12](https://github.com/RolnickLab/ClimateSet/issues/12)). Hope that helps a little. I do not know about your questions regarding internal/scores or LLWeighted_RMSE_WeatherBench code.

**Comment by hassony2** [comment]
Thank you for taking the time to answer this @blutjens, it does help  :)

To double-check my understanding, the reproduced results from your colleague were still with the [issue 12](https://github.com/RolnickLab/ClimateSet/issues/12), right ?

**Comment by blutjens** [comment]
yes, correct. The code that reproduces the numbers would have issue 12.

**Comment by hassony2** [comment]
Thank you for clarifying :)
Also, to partly answer my own questions, I could match the numbers in Table 5 to the [average_stats_single_mean.csv](https://github.com/RolnickLab/ClimateSet/blob/66d724026012d5671817eaf0460ea720b95d8f9f/internal/scores/average_stats_single_mean.csv) file, for instance 0.413 for column test/ssp245_NorESM2-LM/pr/llrmse_climax, row ['NorESM2-LM', 'climax_frozen', 'run2', 'single_emulator', 'tas+pr'], confirming (1) that indeed the intended reported metrics are llrmse_climax.
